#!/usr/bin/env python3
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  data-dir:
    description: filepath for setting the ZooKeeper dataDir option
    type: string
    default: "/opt/zookeeper"
  log-dir: 
    description: filepath for setting the ZooKeeper dataLogDir option
    type: string
    default: "/logs/zookeeper"
  tick-time: 
    description: length of a single tick, in milliseconds, that ZooKeeper uses as the basic time unit to regulate timeouts
    type: int
    default: 2000
  init-limit: 
    description: timeouts ZooKeeper uses to limit the length of time the ZooKeeper servers in quorum have to connect to a leader
    type: int
    default: 5
  sync-limit: 
    description: maximum number of ticks for the followers to wait to synchronize with the leader before the followers time out
    type: int
    default: 2
